# Generated by Django 5.0.7 on 2024-07-28 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinanzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Gastos',
            new_name='Gasto',
        ),
        migrations.RenameModel(
            old_name='Ingresos',
            new_name='Ingreso',
        ),
    ]
